### ISSUE TITLE
Not able to install on Node 20 and NPM 9

### ISSUE THREAD

**Issue by ashishpawar517** [huytd/idea-cli#1]
I tried installing the `install.sh` file, but getting this error . 
```sudo ./install.sh
npm notice 
npm notice New patch version of npm available! 9.8.0 -> 9.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.1
npm notice Run npm install -g npm@9.8.1 to update!
npm notice 
npm ERR! code 1
npm ERR! path /Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
npm ERR! Failed to execute '/opt/homebrew/Cellar/node/20.5.0/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64' (1)
npm ERR!   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.6.38
npm ERR! node-pre-gyp info using node@20.5.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64/node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v115-darwin-arm64.tar.gz
npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v115-darwin-arm64.tar.gz
npm ERR! node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v115-darwin-arm64.tar.gz 
npm ERR! node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@20.5.0 (node-v115 ABI) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v115-darwin-arm64.tar.gz 
npm ERR! node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v115-darwin-arm64.tar.gz 
npm ERR! node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@20.5.0 (node-v115 ABI) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http Connection closed while downloading tarball file 
npm ERR! gypgyp info it worked if it ends with ok
npm ERR!  info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@20.5.0 | darwin | arm64
npm ERR! info using node@20.5.0 | darwin | arm64
npm ERR! gyp gypinfo info  okok 
npm ERR!  
npm ERR! gypgyp  infoinfo  it worked if it ends withit worked if it ends with ok
npm ERR!  ok
npm ERR! gypgyp  infoinfo  usingusing node-gyp@9.4.0
npm ERR!  node-gyp@9.4.0
npm ERR! gypgyp  info usinginfo node@20.5.0 | darwin | arm64
npm ERR!  using node@20.5.0 | darwin | arm64
npm ERR! gyp info gypfind Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR!  info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gypgyp http GET https://nodejs.org/download/release/v20.5.0/node-v20.5.0-headers.tar.gz
npm ERR!  http GET https://nodejs.org/download/release/v20.5.0/node-v20.5.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v20.5.0/node-v20.5.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v20.5.0/node-v20.5.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v20.5.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v20.5.0/SHASUMS256.txt
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/aashish/Library/Caches/node-gyp/20.5.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/aashish/Library/Caches/node-gyp/20.5.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/aashish/Library/Caches/node-gyp/20.5.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp http GET https://nodejs.org/download/release/v20.5.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v20.5.0/SHASUMS256.txt
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/aashish/Library/Caches/node-gyp/20.5.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/aashish/Library/Caches/node-gyp/20.5.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/aashish/Library/Caches/node-gyp/20.5.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@20.5.0 | darwin | arm64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! gyp info ok 
npm ERR! /bin/sh: python: command not found
npm ERR! make: *** [Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Darwin 22.1.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/20.5.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64"
npm ERR! gyp ERR! cwd /Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3
npm ERR! gyp ERR! node -v v20.5.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node/20.5.0/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! node-pre-gyp ERR! System Darwin 22.1.0
npm ERR! node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/20.5.0/bin/node" "/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3
npm ERR! node-pre-gyp ERR! node -v v20.5.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.6.38
npm ERR! node-pre-gyp ERR! not ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@20.5.0 | darwin | arm64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! /bin/sh: python: command not found
npm ERR! make: *** [Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Darwin 22.1.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/20.5.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64"
npm ERR! gyp ERR! cwd /Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3
npm ERR! gyp ERR! node -v v20.5.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /Users/aashish/.npm/_logs/2023-08-04T05_04_37_724Z-debug-0.log
aashish@Aashishs-MacBook-Air idea-cli-master % 
aashish@Aashishs-MacBook-Air idea-cli-master % node --version
v20.5.0
aashish@Aashishs-MacBook-Air idea-cli-master % npm --version
9.8.0
aashish@Aashishs-MacBook-Air idea-cli-master % npm i
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /Users/aashish/.npm/_cacache/tmp/ead628cc
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 501:20 "/Users/aashish/.npm"

npm ERR! A complete log of this run can be found in: /Users/aashish/.npm/_logs/2023-08-04T05_07_06_209Z-debug-0.log
aashish@Aashishs-MacBook-Air idea-cli-master % sudo chown -R 501:20 "/Users/aashish/.npm"
aashish@Aashishs-MacBook-Air idea-cli-master % npm i
npm ERR! code 1
npm ERR! path /Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
npm ERR!   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
npm ERR! Failed to execute '/opt/homebrew/Cellar/node/20.5.0/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.6.38
npm ERR! node-pre-gyp info using node@20.5.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64/node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v115-darwin-arm64.tar.gz
npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v115-darwin-arm64.tar.gz
npm ERR! node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v115-darwin-arm64.tar.gz 
npm ERR! node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@20.5.0 (node-v115 ABI) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v115-darwin-arm64.tar.gz 
npm ERR! node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v115-darwin-arm64.tar.gz 
npm ERR! node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@20.5.0 (node-v115 ABI) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http Connection closed while downloading tarball file 
npm ERR! gypgyp info it worked if it ends with ok
npm ERR!  info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp gyp infoinfo using node@20.5.0 | darwin | arm64
npm ERR!  using node-gyp@9.4.0
npm ERR! gyp info using node@20.5.0 | darwin | arm64
npm ERR! gyp info gyp info ok 
npm ERR! ok 
npm ERR! gyp info gypit worked if it ends with ok
npm ERR!  info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@20.5.0 | darwin | arm64
npm ERR! gyp info using node@20.5.0 | darwin | arm64
npm ERR! gyp info gypfind Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR!  info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/aashish/Library/Caches/node-gyp/20.5.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/aashish/Library/Caches/node-gyp/20.5.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/aashish/Library/Caches/node-gyp/20.5.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/aashish/Library/Caches/node-gyp/20.5.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/aashish/Library/Caches/node-gyp/20.5.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/aashish/Library/Caches/node-gyp/20.5.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info ok 
npm ERR! gypgyp info it worked if it ends with ok
npm ERR!  info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@20.5.0 | darwin | arm64
npm ERR! gyp info using node@20.5.0 | darwin | arm64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! /bin/sh: python: command not found
npm ERR! /bin/sh: python: command not found
npm ERR! make: *** [Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c] Error 127
npm ERR! make: *** [Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c] Error 127
npm ERR! gypgyp ERR! build error 
npm ERR!  ERR! build error 
npm ERR! gyp ERR!gyp stack  Error: `make` failed with exit code: 2
npm ERR! ERR!gyp  stackERR! Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR!  gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stackstack     at ChildProcess.emit (node:events:514:28)
npm ERR!      at ChildProcess.emit (node:events:514:28)
npm ERR! gypgyp  ERR!ERR!  stackstack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR!      at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Darwin 22.1.0
npm ERR! gyp ERR! System Darwin 22.1.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/20.5.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64"
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/20.5.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64"
npm ERR! gyp ERR! cwd /Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3
npm ERR! gyp ERR!gyp  cwdERR! /Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3
npm ERR!  node -v v20.5.0
npm ERR! gyp ERR!gyp  node -vERR! v20.5.0
npm ERR!  node-gyp -v v9.4.0
npm ERR! gyp ERR! gypnode-gyp -v  v9.4.0
npm ERR! ERR! not ok 
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node/20.5.0/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/lib/binding/node-v115-darwin-arm64' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! node-pre-gyp ERR! System Darwin 22.1.0
npm ERR! node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/20.5.0/bin/node" "/Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/aashish/Downloads/idea-cli-master/node_modules/sqlite3
npm ERR! node-pre-gyp ERR! node -v v20.5.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.6.38
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /Users/aashish/.npm/_logs/2023-08-04T05_08_07_946Z-debug-0.log
```
I have node `20.5.0` and npm `9.8.0`

**Comment by huytd** [comment]
This is environment issue. I'd recommend take a closer look at the error messages and install the missing stuff on your environment.
